'\" -*- coding: UTF-8 -*-
.TH psmaster 1
.SH NAME
psmaster \- master patch a PlayStation 2 disc image
.SH SYNOPSIS
.nf
\fBpsmaster\fR [\fIOPTION\fR] [\fIFILE\fR]
\fBpsmaster\fR [-h|-V]
.SH DESCRIPTION
.I psmaster
can "master patch" a PlayStation 2 disc image given in FILE, allowing
it to be run on a TEST console.
.P
Sony produced a special set of PlayStation 2 consoles, called TEST
systems. These systems differ from retail models primarily in their
ability to play games from CD-R and DVD-R media, allowing copied games
to be run. However, these consoles will only recognize burned media as
valid if they contain "master data" in sectors 12 and 13 of the disc.
These sectors are zeroed out on all retail games. Using \fIpsmaster\fR,
it is possible to patch a retail disc image to contain master data,
allowing the image to be burned to disc and run on a PlayStation 2 TEST
console.
.SH OPTIONS
.TP
.B \-h
Print a usage message on standard output and exit successfully.
.TP
.B \-l
List master data from FILE.
.TP
.B \-b
Create new master data in FILE.
.TP
.B \-d \fIDATE\fR
Use \fIDATE\fR as the master data creation date, instead of the current
date. The date format is YYYYMMDD.
.TP
.B \-p \fIPCODE\fR
Use \fIPCODE\fR as the game product code, instead of auto-detecting.
The product code format is ABCD-12345.
.TP
.B \-P \fINAME\fR
Use \fINAME\fR as the producer name in the master data.
.TP
.B \-r \fINUM\fR
Set the disc region by number. Valid region numbers are:
.sp
.nf
.TA 2n 20n
\fI1\fR Japan
\fI2\fR America
\fI4\fR Europe
\fI8\fR China
.TP
.B \-V
Print version information on standard output and exit successfully.
.SH AUTHOR
Jason Benaim <jrra@jrra.zone>
.SH COPYRIGHT
Copyright \(co 2023 Jason Benaim.
.br
Licensed under the GNU GPL version 3 or later.
.br
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR psps (1)
